### ISSUE TITLE
Error when use camvid_data_loader.py

### ISSUE THREAD

**Issue by wlwsea** [0bserver07/One-Hundred-Layers-Tiramisu#9]
hi @0bserver07 ,

When i use `python camvid_data_loader.py`, it showed the following error,
```
Traceback (most recent call last):
  File "camvid_data_loader.py", line 34, in <module>
    train_data, train_label = load_data("train")
  File "camvid_data_loader.py", line 27, in load_data
    data.append(np.rollaxis(normalized(cv2.imread(os.getcwd() + txt[i][0][7:])[136:,256:]),2))
TypeError: 'NoneType' object has no attribute '__getitem__'
```
I have installed all the libs in your requirement.txt .
Do you know what's the reason of that error and how can i deal with it ?

Thanks a ton!

**Comment by wlwsea** [comment]
I want to train fc-densenet in my own dataset.
So I just copy my data into CamVid and delete the origin data.
I also modify train.txt test.txt val.txt .
But, when i use `python camvid_data_loader.py`, it showed the following error,
```
Traceback (most recent call last):
  File "camvid_data_loader.py", line 34, in <module>
    train_data, train_label = load_data("train")
  File "camvid_data_loader.py", line 27, in load_data
    data.append(np.rollaxis(normalized(cv2.imread(os.getcwd() + txt[i][0][7:])[136:,256:]),2))
TypeError: 'NoneType' object has no attribute '__getitem__'
```
Can i ask how to modify camvid_data_loader.py?  Are there any other solutions?
Thank you !

**Comment by lnuchiyo** [comment]
@wlwsea  excuse me,have you solve the problem?
i have meet the same trouble ,can you tell me some suggestion? thanks a lot!
